services:
  frontend:
    image: frontend
    container_name: alr_frontend
    build: bingo-driven_front-end/
    ports:
      - 8080:80
    networks:
      - alr_network
networks:
  alr_network:
    external: true
      


